version: "3"
services:
  sound-detect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sound-detect
    command: python /server/manage.py runserver 0.0.0.0:8000
    hostname: sound-detect
    tty: true
    ports:
      - "8000:8000"
    environment:
      TZ: 'Asia/Tokyo'